// Code generated by templ DO NOT EDIT.

package templates

import "github.com/a-h/templ"
import "context"
import "io"

func GoodbyeTemplate(message string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		_, err = io.WriteString(w, "<turbo-frame")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " id=\"app-container\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<p>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(message))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</p>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</turbo-frame>")
		if err != nil {
			return err
		}
		return err
	})
}

